In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import optim


In [2]:
VOCAB = {'A':1,'B':2,'C':3,'D':4,'E':5}
train_data = [1,2,3,4,5]
train_label = [1,1,1,0,0]

In [3]:
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.embedding = nn.Embedding(7,3,padding_idx=0)
        self.fc = nn.Linear(3,1)

    def forward(self, x):
        embed = self.embedding(x)
        out = self.fc(embed)
        sigmoid_out=torch.sigmoid(out)
        return sigmoid_out

In [4]:
myModel = MyModel()
myModel.forward(torch.tensor(1))

tensor([0.5338], grad_fn=<SigmoidBackward0>)

In [5]:
lossFn = nn.functional.binary_cross_entropy

print(lossFn(torch.tensor(0.1),torch.tensor(1.0)))
print(lossFn(torch.tensor(0.9),torch.tensor(1.0)))

tensor(2.3026)
tensor(0.1054)


In [6]:
learning_rate = 1e-2
optimizer = torch.optim.Adam(myModel.parameters(), lr=learning_rate)
epoch = 100

In [7]:
for i in range(epoch):
    # print("-------第 {} 轮训练开始-------".format(i + 1))
    # 训练步骤开始
    myModel.train()
    for idx in range(len(train_label)):
        data = torch.tensor(train_data[idx])
        label = torch.tensor([train_label[idx]],dtype=torch.float)
        output = myModel(data)  # 求模型的输出
        loss = lossFn(output, label)  # 求loss


        # 优化器优化模型
        optimizer.zero_grad()  # 梯度清零
        loss.backward()  # 求梯度
        optimizer.step()  # 更新参数

In [8]:
myModel(torch.tensor(1)),myModel(torch.tensor(2)),myModel(torch.tensor(3)),myModel(torch.tensor(4)),myModel(torch.tensor(5))

(tensor([0.9956], grad_fn=<SigmoidBackward0>),
 tensor([0.9961], grad_fn=<SigmoidBackward0>),
 tensor([0.9923], grad_fn=<SigmoidBackward0>),
 tensor([0.0212], grad_fn=<SigmoidBackward0>),
 tensor([0.0071], grad_fn=<SigmoidBackward0>))